MONGO_URI = "mongodb+srv://new-user-69:6920@cluster0.ooazf0k.mongodb.net/?appName=Cluster0"

[cloudinary]
cloud_name = "aznid9u6"
api_key = "577148886157263"
api_secret = "vSjwnqkjwYJHNDf0TZ68bJ1dp0M"